ecommerce/urls.py
from django.contrib import admin
from django.urls import path
from products import views as product_views
from django.conf import settings
from django.conf.urls.static import static
from users import views as users_views

#for login view
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', product_views.index, name='index'),
    path('product_detail/<int:pk>/', product_views.product_detail, name='product_detail'),
    path('add_review/', product_views.add_review, name='add_review'),
    path('add_to_wishlist/', product_views.add_to_wishlist, name='add_to_wishlist'),
    path('register/', users_views.register, name='register'),
    path('profile/', users_views.profile, name='profile'),
    path('profile_edit/', users_views.profile_edit, name='profile_edit'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('subscribe/', product_views.subscribe, name='subscribe'),
    path('add_to_cart/', product_views.add_to_cart, name='add_to_cart'),
    path('checkout/', product_views.checkout, name='checkout'),
    path('remove_item/', product_views.remove_item, name='remove_item'),
    path('place_order/', product_views.place_order, name='place_order'),
    path('charge/', product_views.charge, name='charge'),
    path('success/<str:args>/', product_views.successMsg, name="success"),
    path('search/', product_views.search, name='search'),
    path('sort/', product_views.sort, name='sort'),
    path('price_filter/', product_views.price_sort, name='price_sort'),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product
from django.utils import timezone
from django import forms

# Create your models here.
class Profile(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return f'{self.user.username}'

class Address(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	address_line = models.CharField(max_length=100)
	zip_code = models.CharField(max_length=12)
	city = models.CharField(max_length=1024)
	country = models.CharField(max_length=30)

	def __str__(self):
		return f'{self.address_line}'

class Order(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	date_ordered = models.DateTimeField(default=timezone.now)
	quantity_of_product = models.IntegerField(default=1)

	def __str__(self):
		return f'Ordered by {self.user} - {self.product}'

class Wishlist(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)

	def __str__(self):
		return f'{self.product}'


class SubscribedUsers(models.Model):
    email = models.CharField(unique=True, max_length=50)
    def __str__(self):
	    return f'{self.email}'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email']

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from users.forms import UserRegisterForm, UserUpdateForm
from django.contrib import messages
from .models import Profile
#import login_required decorator for profile
from django.contrib.auth.decorators import login_required

def register(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f'Account was created for {username}')
			return redirect('login')
		else:
			messages.warning(request, 'Something went wrong. Please make sure you satisfy password conditions')
			form = UserRegisterForm()
			return render(request, 'users/register.html', {'form': form})
	else:
		form = UserRegisterForm()
		return render(request, 'users/register.html', {'form': form})
@login_required
def profile(request):
	return render(request, 'users/profile.html')


@login_required
def profile_edit(request):
	if request.method == 'POST':
		u_form = UserUpdateForm(request.POST, instance=request.user)
		if u_form.is_valid():
			u_form.save()
			messages.success(request, f'Your account has been updated!')
			return redirect('profile')

	else:
		u_form = UserUpdateForm(instance=request.user)

	context = {
	'u_form': u_form,
	}
	return render(request, 'users/profile_edit.html', context)

users/templates/users/login.html
{% extends 'products/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
	{% if messages %}
	{% for message in messages %}
		<div class="alert alert-{{message.tags}}" role="alert">
			{{ message }}
		  </div>
	{% endfor %}
{% endif %}
 <h4> Login </h4>

	<form method="POST">
		{% csrf_token %}
		{{ form | crispy }}
		<button type="submit" class="btn btn-primary"> Login </button>
	</form>
	<span> Need an account? <a class="btn btn-danger" href="{% url 'register' %}"> Register </a></span>
</div>
{% endblock content %}

users/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<h5> You have been logged out </h5>
	<span> <a href="{% url 'login' %}"> Login again </a></span>
</body>
</html>

users/templates/users/profile.html
{% extends 'products/base.html' %}
{% load static %}
{% block content %}

<!-- BREADCRUMB -->
<div id="breadcrumb" class="section">
	<!-- container -->
	<div class="container">
		<!-- row -->
		<div class="row">
			<div class="col-md-12">
				<h3 class="breadcrumb-header">User Profile</h3>
				<ul class="breadcrumb-tree">
					<li><a href="{% url 'index' %}">Home</a></li>
					<li class="active"> User Profile </li>
				</ul>
			</div>
		</div>
		<!-- /row -->

	</div>
	<!-- /container -->
</div>
<!-- /BREADCRUMB -->
<div class="container padding-bottom-3x mb-2">
    <div class="row">
        {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{message.tags}}" role="alert">
                {{ message }}
              </div>
        {% endfor %}
    {% endif %}
        <div class="col-lg-4 ">
            <aside class="user-info-wrapper">

                <div class="user-info">
                    <div class="user-data">
                        <h4> {{ request.user.username }}</h4><span>Joined February 06, 2017</span>
                        <br>
                        <a class="btn btn-danger" href="{% url 'profile_edit' %}"> Update Profile </a>
                    </div>
                </div>
            </aside>
            <nav class="list-group">
                <a class="list-group-item with-badge" href="#orders"><i class=" fa fa-th"></i>Orders<span class="badge badge-primary badge-pill">{{ user.order_set.count }}</span></a>
                <a class="list-group-item with-badge" href="#wishlist"><i class="fa fa-heart"></i>Wishlist<span class="badge badge-primary badge-pill"> {{ user.wishlist_set.count }}</span></a>
            </nav>
        </div>
        <div class="col-lg-8">
            <div class="padding-top-2x mt-2 hidden-lg-up"></div>
            <!-- Wishlist Table-->
            <div class="table-responsive wishlist-table margin-bottom-none">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Orders</th>
                            <th class="text-center"><a class="btn btn-sm btn-outline-danger" href="#">Your orders</a></th>
                        </tr>
                        <a id="orders"></a>
                    </thead>
                    <tbody>
                        {% for ordered_product in user.order_set.all %}
                            <tr>
                                <td>
                                    <div class="product-item">
                                        <div id="product-main-img">
                                            <div class="product-preview">
                                        <a class="product-thumb" href="#"><img src="{{ ordered_product.product.product_image.url }}" alt="Product"></a>
                                                </div>
                                                </div>
                                        <div class="product-info">
                                            <h4 class="product-title"><a href="/product_detail/{{ ordered_product.product.id }}/">{{ ordered_product.product }}</a></h4>
                                            <div class="text-lg text-medium text-muted">${{ ordered_product.product.product_price }}</div>
                                            <div>Ordered On:
                                                <div class="d-inline text-success"> {{ ordered_product.date_ordered }} </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Wishlist </th>
                            <a id="wishlist"></a>
                        </tr>
                    </thead>
                    <tbody>
                        {% for wishes in user.wishlist_set.all %}
                        <tr>

                            <td>
                                <div class="product-item">
                                    <div id="product-main-img">
                                    <div class="product-preview">
                                    <img src="{{ wishes.product.product_image.url }}" alt="Product">
                                    </div>
                                    </div>
                                    <div class="product-info">
                                        <h4 class="product-title"><a href="/product_detail/{{ wishes.product.id }}/"> {{ wishes.product }} </a></h4>
                                        <div class="text-lg text-medium text-muted">${{ wishes.product.product_price }}</div>
                                        <div>Availability:
                                            <div class="d-inline text-warning"> {{ wishes.product.product_status }}</div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>

	                    {% endfor %}
                        </tbody>
                        </table>

            </div>
            <hr class="mb-4">


        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/profile_edit.html
{% extends 'products/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="container">
		<div class="row">
			<form method="POST">
				{% csrf_token %}
				{{ u_form | crispy }}
				<button type="submit" class="btn btn-danger"> Update </button>
				<a href="{% url 'profile' %}" class="btn btn-info" role="button"> Cancel </a>
			</form>
		</div>
	</div>

{% endblock content %}

users/templates/users/register.html
{% extends 'products/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
	{% if messages %}
		{% for message in messages %}
		<div class="alert alert-{{message.tags}}" role="alert">
			{{ message }}
		  </div>
		{% endfor %}
	{% endif %}
	<h5> Register </h5>
	<form method="POST">
		{% csrf_token %}
		{{ form | crispy  }}
		<button type="submit" class="btn btn-danger"> Sign Up </button>
	</form>
	</div>
{% endblock content %}